apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  volumeName: my-local-pv
  storageClassName: my-local-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

